// topics
const TOPIC_ALL_NOTIFY = "ALL";
const FILTER_URGENT = "URGENT_NOTIFICATIONS";
const PROMOTIONAL_NOTIFICATION = "PROMOTION_NOTIFICATIONS";
const TOPIC_EMAIL = "EMAIL";
const TOPIC_SMS = "SMS";
const TOPIC_DEVICE = "DEVICE";
const PROMOTIONAL = "PROMOTIONAL";
const OTP = "OTP";
const TRANSACTIONAL = "TRANSACTIONAL";


const MESSAGE_TYPES = {
    PROMOTIONAL,
    OTP,
    TRANSACTIONAL
};

module.exports = {
    TOPIC_ALL_NOTIFY,
    FILTER_URGENT,
    PROMOTIONAL_NOTIFICATION,
    MESSAGE_TYPES,
    TOPIC_EMAIL,
    TOPIC_SMS,
    TOPIC_DEVICE
}